import { check } from 'express-validator';

export const createHotelValidation = [
  check('en_name')
    .bail()
    .notEmpty()
    .withMessage('Name is required')
    .bail()
    .isString()
    .withMessage('Name must be a string')
    .bail()
    .isLength({ min: 3 })
    .withMessage('Name must be at least 3'),
  check('dr_name')
    .bail()
    .notEmpty()
    .withMessage('Name is required')
    .bail()
    .isString()
    .withMessage('Name must be a string')
    .bail()
    .isLength({ min: 3 })
    .withMessage('Name must be at least 3'),
  check('ps_name')
    .bail()
    .notEmpty()
    .withMessage('Name is required')
    .bail()
    .isString()
    .withMessage('Name must be a string')
    .bail()
    .isLength({ min: 3 })
    .withMessage('Name must be at least 3'),
  check('en_description')
    .bail()
    .notEmpty()
    .withMessage('Description is required')
    .bail()
    .isString()
    .withMessage('Description must be a string')
    .bail()
    .isLength({ min: 3 })
    .withMessage('Description must be at least 3'),
  check('dr_description')
    .bail()
    .notEmpty()
    .withMessage('Description is required')
    .bail()
    .isString()
    .withMessage('Description must be a string')
    .bail()
    .isLength({ min: 3 })
    .withMessage('Description must be at least 3'),
  check('ps_description')
    .bail()
    .notEmpty()
    .withMessage('Description is required')
    .bail()
    .isString()
    .withMessage('Description must be a string')
    .bail()
    .isLength({ min: 3 })
    .withMessage('Description must be at least 3'),
  check('en_address')
    .bail()
    .notEmpty()
    .withMessage('Address is required')
    .bail()
    .isString()
    .withMessage('Address must be a string')
    .bail()
    .isLength({ min: 3 })
    .withMessage('Address must be at least 3'),
  check('dr_address')
    .bail()
    .notEmpty()
    .withMessage('Address is required')
    .bail()
    .isString()
    .withMessage('Address must be a string')
    .bail()
    .isLength({ min: 3 })
    .withMessage('Address must be at least 3'),
  check('ps_address')
    .bail()
    .notEmpty()
    .withMessage('Address is required')
    .bail()
    .isString()
    .withMessage('Address must be a string')
    .bail()
    .isLength({ min: 3 })
    .withMessage('Address must be at least 3'),
  check('email').bail().notEmpty().withMessage('Email is required').bail().isEmail().withMessage('Email must be a valid email'),
  check('phone')
    .bail()
    .notEmpty()
    .withMessage('Phone is required')
    .bail()
    .isString()
    .withMessage('Phone must be a string')
    .bail()
    .isLength({ min: 3 })
    .withMessage('Phone must be at least 3'),
  check('website')
    .bail()
    .notEmpty()
    .withMessage('Website is required')
    .bail()
    .isString()
    .withMessage('Website must be a string')
    .bail()
    .isLength({ min: 3 })
    .withMessage('Website must be at least 3'),
  check('rating')
    .bail()
    .notEmpty()
    .withMessage('Rating is required')
    .bail()
    .isNumeric()
    .withMessage('Rating must be a number')
    .custom(value => value >= 0 && value <= 5)
    .withMessage('Rating must be between 0 and 5'),
  check('lat').bail().notEmpty().withMessage('Latitude is required').bail().isNumeric().withMessage('Latitude must be a number'),
  check('lng').bail().notEmpty().withMessage('Longitude is required').bail().isNumeric().withMessage('Longitude must be a number'),
  check('province_id').bail().notEmpty().withMessage('Province is required').bail().isMongoId().withMessage('Province must be a valid ID'),
  check('googleMapUrl').bail().isURL().withMessage('Google Map URL must be a valid URL'),
];
